name: histouric_web
description: A new Flutter project for the HisTouric Web App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  shared_preferences: ^2.2.0
  universal_html: ^2.2.3
  js: ^0.6.7
  url_strategy: ^0.2.0
  google_maps_flutter_web: ^0.5.4+2
  google_maps_flutter: ^2.5.0
  pointer_interceptor: ^0.9.3+6
  card_swiper: ^3.0.1
  dots_indicator: ^3.0.0
  animate_do: ^3.1.2
  flutter_polyline_points: ^2.0.0
  file_picker: ^5.5.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
