name: histouric_web
description: A new Flutter project for the HisTouric Web App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  shared_preferences: ^2.2.0
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
